package com.maskan.mobileapp.ui.auth

import android.content.Context
import androidx.credentials.CredentialManager
import androidx.credentials.CustomCredential
import androidx.credentials.GetCredentialRequest
import com.google.android.libraries.identity.googleid.GetGoogleIdOption
import com.google.android.libraries.identity.googleid.GoogleIdTokenCredential
import com.maskan.mobileapp.R

/**
 * Launches the system Credential Manager account picker and returns a Google
 * ID token, which [com.maskan.mobileapp.data.repository.AuthRepository.signInLandlordWithGoogle]
 * exchanges for a Firebase session. `default_web_client_id` is generated by the
 * google-services Gradle plugin from the Web OAuth client in google-services.json
 * — not something to hardcode here.
 */
suspend fun requestGoogleIdToken(context: Context): String {
    val googleIdOption = GetGoogleIdOption.Builder()
        .setFilterByAuthorizedAccounts(false)
        .setServerClientId(context.getString(R.string.default_web_client_id))
        .build()
    val request = GetCredentialRequest.Builder().addCredentialOption(googleIdOption).build()

    val result = CredentialManager.create(context).getCredential(context, request)
    val credential = result.credential
    if (credential !is CustomCredential || credential.type != GoogleIdTokenCredential.TYPE_GOOGLE_ID_TOKEN_CREDENTIAL) {
        error("Unexpected credential type from Credential Manager")
    }
    return GoogleIdTokenCredential.createFrom(credential.data).idToken
}
